---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/data/sonarr:/config
      - /media/media/TV:/tv #optional
      - /downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/data/radarr:/config
      - /media/media/movies:/movies #optional
      - /downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/data//lidarr/config:/config
      - /media/media/music:/music #optional
      - /downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/data/bazarr/config:/config
      - /media/media/movies:/movies #optional
      - /media/media/TV:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - AUTO_UPDATE=true #optional
    volumes:
      - /docker/data/jackett:/config
      - /downloads/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped