---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /docker/data/homer/:/www/assets
    ports:
      - 80:8080
    #environment:
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
  homer-e:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer-External
    volumes:
      - /docker/data/homer-External/:/www/assets
    ports:
      - 85:8080
    #environment:
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
