---
version: "2.1"
services:
  firefox:
    image: lscr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/data/firefox/:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped