version: "3"

services:
  mc:
    image: itzg/minecraft-server
    volumes:
      - /docker/data/minecraft:/data
      - /docker/data/minecraft/plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      OPS: "Warren_r"
    tty: true
    stdin_open: true
    restart: unless-stopped
  creative:
    image: itzg/minecraft-server
    volumes:
      - /docker/data/minecraft-creative:/data
    ports:
      - 25566:25565
    environment:
      EULA: "TRUE"
      OPS: "Warren_r"
    tty: true
    stdin_open: true
    restart: unless-stopped
